
services:
- type: web
  name: app-backend
  env: go
  rootDir: backend
  buildCommand: go build -o app .
  startCommand: ./app
- type: web
  name: app-frontend
  branch: main
  env: static
  buildCommand: cd frontend; yarn; yarn build
  staticPublishPath: ./frontend/build/
  # Build and deploy `app-frontend` if any `js` file changes,
  # but ignore any test files.
  buildFilter:
    paths:
    - frontend/**/*.js
    ignoredPaths:
    - frontend/**/*.test.js